--Create usertables
DROP TABLE IF EXISTS users;
CREATE TABLE `plants`.`users` ( `username` TEXT NOT NULL , `password` TEXT NOT NULL , `address` TEXT NOT NULL, `salt` TEXT NOT NULL) ENGINE = InnoDB;


--Create producttable
DROP TABLE IF EXISTS products;
CREATE TABLE `plants`.`products`(`id` INT NOT NULL, `product_name` TEXT NOT NULL, `price` REAL NOT NULL);
INSERT INTO `products`(`id`, `product_name`, `price`)
VALUES (1, 'Monstera', 14.99), (2, 'Peperomia', 7.99), (3, 'Cactus', 9.99), (4, 'Succulent', 12.99);


--Create table passwordblacklist
CREATE TABLE `plants`.`passwordblacklist` ( `password` TEXT NOT NULL ) ENGINE = InnoDB;
INSERT INTO passwordblacklist (password) VALUES ('123456');
INSERT INTO passwordblacklist (password) VALUES ('password');
INSERT INTO passwordblacklist (password) VALUES ('12345678');
INSERT INTO passwordblacklist (password) VALUES ('qwerty');
INSERT INTO passwordblacklist (password) VALUES ('123456789');
INSERT INTO passwordblacklist (password) VALUES ('12345');
INSERT INTO passwordblacklist (password) VALUES ('1234');
INSERT INTO passwordblacklist (password) VALUES ('111111');
INSERT INTO passwordblacklist (password) VALUES ('1234567');
INSERT INTO passwordblacklist (password) VALUES ('dragon');
INSERT INTO passwordblacklist (password) VALUES ('123123');
INSERT INTO passwordblacklist (password) VALUES ('baseball');
INSERT INTO passwordblacklist (password) VALUES ('abc123');
INSERT INTO passwordblacklist (password) VALUES ('football');
INSERT INTO passwordblacklist (password) VALUES ('monkey');
INSERT INTO passwordblacklist (password) VALUES ('letmein');
INSERT INTO passwordblacklist (password) VALUES ('696969');
INSERT INTO passwordblacklist (password) VALUES ('shadow');
INSERT INTO passwordblacklist (password) VALUES ('master');
INSERT INTO passwordblacklist (password) VALUES ('666666');
INSERT INTO passwordblacklist (password) VALUES ('qwertyuiop');
INSERT INTO passwordblacklist (password) VALUES ('123321');
INSERT INTO passwordblacklist (password) VALUES ('mustang');
INSERT INTO passwordblacklist (password) VALUES ('1234567890');
INSERT INTO passwordblacklist (password) VALUES ('michael');
INSERT INTO passwordblacklist (password) VALUES ('654321');
INSERT INTO passwordblacklist (password) VALUES ('pussy');
INSERT INTO passwordblacklist (password) VALUES ('superman');
INSERT INTO passwordblacklist (password) VALUES ('1qaz2wsx');
INSERT INTO passwordblacklist (password) VALUES ('7777777');
INSERT INTO passwordblacklist (password) VALUES ('fuckyou');
INSERT INTO passwordblacklist (password) VALUES ('121212');
INSERT INTO passwordblacklist (password) VALUES ('000000');
INSERT INTO passwordblacklist (password) VALUES ('qazwsx');
INSERT INTO passwordblacklist (password) VALUES ('123qwe');
INSERT INTO passwordblacklist (password) VALUES ('killer');
INSERT INTO passwordblacklist (password) VALUES ('trustno1');
INSERT INTO passwordblacklist (password) VALUES ('jordan');
INSERT INTO passwordblacklist (password) VALUES ('jennifer');
INSERT INTO passwordblacklist (password) VALUES ('zxcvbnm');
INSERT INTO passwordblacklist (password) VALUES ('asdfgh');
INSERT INTO passwordblacklist (password) VALUES ('hunter');
INSERT INTO passwordblacklist (password) VALUES ('buster');
INSERT INTO passwordblacklist (password) VALUES ('soccer');
INSERT INTO passwordblacklist (password) VALUES ('harley');
INSERT INTO passwordblacklist (password) VALUES ('batman');
INSERT INTO passwordblacklist (password) VALUES ('andrew');
INSERT INTO passwordblacklist (password) VALUES ('tigger');
INSERT INTO passwordblacklist (password) VALUES ('sunshine');
INSERT INTO passwordblacklist (password) VALUES ('iloveyou');
INSERT INTO passwordblacklist (password) VALUES ('fuckme');
INSERT INTO passwordblacklist (password) VALUES ('2000');
INSERT INTO passwordblacklist (password) VALUES ('charlie');
INSERT INTO passwordblacklist (password) VALUES ('robert');
INSERT INTO passwordblacklist (password) VALUES ('thomas');
INSERT INTO passwordblacklist (password) VALUES ('hockey');
INSERT INTO passwordblacklist (password) VALUES ('ranger');
INSERT INTO passwordblacklist (password) VALUES ('daniel');
INSERT INTO passwordblacklist (password) VALUES ('starwars');
INSERT INTO passwordblacklist (password) VALUES ('klaster');
INSERT INTO passwordblacklist (password) VALUES ('112233');
INSERT INTO passwordblacklist (password) VALUES ('george');
INSERT INTO passwordblacklist (password) VALUES ('asshole');
INSERT INTO passwordblacklist (password) VALUES ('computer');
INSERT INTO passwordblacklist (password) VALUES ('michelle');
INSERT INTO passwordblacklist (password) VALUES ('jessica');
INSERT INTO passwordblacklist (password) VALUES ('pepper');
INSERT INTO passwordblacklist (password) VALUES ('1111');
INSERT INTO passwordblacklist (password) VALUES ('zxcvbn');
INSERT INTO passwordblacklist (password) VALUES ('555555');
INSERT INTO passwordblacklist (password) VALUES ('11111111');
INSERT INTO passwordblacklist (password) VALUES ('131313');
INSERT INTO passwordblacklist (password) VALUES ('freedom');
INSERT INTO passwordblacklist (password) VALUES ('777777');
INSERT INTO passwordblacklist (password) VALUES ('pass');
INSERT INTO passwordblacklist (password) VALUES ('fuck');
INSERT INTO passwordblacklist (password) VALUES ('maggie');
INSERT INTO passwordblacklist (password) VALUES ('159753');
INSERT INTO passwordblacklist (password) VALUES ('aaaaaa');
INSERT INTO passwordblacklist (password) VALUES ('ginger');
INSERT INTO passwordblacklist (password) VALUES ('princess');
INSERT INTO passwordblacklist (password) VALUES ('joshua');
INSERT INTO passwordblacklist (password) VALUES ('cheese');
INSERT INTO passwordblacklist (password) VALUES ('amanda');
INSERT INTO passwordblacklist (password) VALUES ('summer');
INSERT INTO passwordblacklist (password) VALUES ('love');
INSERT INTO passwordblacklist (password) VALUES ('ashley');
INSERT INTO passwordblacklist (password) VALUES ('6969');
INSERT INTO passwordblacklist (password) VALUES ('nicole');
INSERT INTO passwordblacklist (password) VALUES ('chelsea');
INSERT INTO passwordblacklist (password) VALUES ('biteme');
INSERT INTO passwordblacklist (password) VALUES ('matthew');
INSERT INTO passwordblacklist (password) VALUES ('access');
INSERT INTO passwordblacklist (password) VALUES ('yankees');
INSERT INTO passwordblacklist (password) VALUES ('987654321');
INSERT INTO passwordblacklist (password) VALUES ('dallas');
INSERT INTO passwordblacklist (password) VALUES ('austin');
INSERT INTO passwordblacklist (password) VALUES ('thunder');
INSERT INTO passwordblacklist (password) VALUES ('taylor');
INSERT INTO passwordblacklist (password) VALUES ('matrix');
